---
title: "(F) Disease Incidence Datasets and hsCRP "
author: "Randy Truong"
date: "2022-12-29"
output: html_document
---

# Installing Packages 

```{r loadPackages, message=FALSE}
library(tidyverse)
library(readr)
```

## Important Terminology: 
CVD -> Cardiovascular Disease           
CRP -> C-Reactive Protein           

```{r loadData, message=FALSE}
fAsianDF <- read_csv("./Data/fData/F_Asian.csv")
fHispanicDF <- read_csv("./Data/fData/F_hispanic.csv")
fBlackDF <- read_csv("./Data/fData/F_non-hispanic_black.csv")
fWhiteDF <- read_csv("./Data/fData/F_non-hispanic_white.csv")
fDF <- read_csv("./Data/fData/allFemales.csv")

```

# Filtering of Data Sets 

In the datasets, we mostly just care about the rows "Diagnosed with CVD" (1),  
"Ever diagnosed with diabetes W5" (11), "log10(hsCRP) W4" (24), "High hsCRP (>3 mg/L) W4" (25), and "Observations" (34).

```{r filterMaleAsian, message=FALSE}

# Remember to rename first row 
fAsianDFClean <- mutate(fAsianDF, Race = "Asian") %>% 
  slice(1, 11, 23, 24, 25, 34) 

fHispanicDFClean <- mutate(fHispanicDF, Race = "Hispanic") %>% 
  slice(1, 11, 23, 24, 25, 34) 

fBlackDFClean <- mutate(fBlackDF, Race = "Black") %>% 
  slice(1, 11, 23, 24, 25, 34) 

fWhiteDFClean <- mutate(fWhiteDF, Race = "White") %>% 
  slice(1, 11, 23, 24, 25, 34) 

fDFClean <- mutate(fDF, Race = "All") %>% 
  slice(1, 11, 23, 24, 25, 34)

colnames(fDFClean)[1] = "...1"

```

```{r createGiantFrame, message=FALSE}
raceList1 <- rbind(fAsianDFClean, fHispanicDFClean)
raceList2 <- rbind(fBlackDFClean, fWhiteDFClean)
raceList3 <- rbind(raceList1, raceList2)
finalRaceListF <- rbind(raceList3, fDFClean)

```


# Data Visualization  

```{r crpByRace}
# Note: The matrix must be race x summary statistics in order of (min, Q1, Q2, Q3, max)
#         [min] [q1] [q2] [q3] [max]
# [Asian]
# [Hispanic]
# [Black]
# [White]

finalRaceListF_CRP <- finalRaceListF %>% 
  slice(3, 9, 15, 21, 27) 

fStats <- list(stats=t(cbind(finalRaceListF_CRP$Minimum,
                 finalRaceListF_CRP$`Percentile 25`,
                 finalRaceListF_CRP$Median,
                 finalRaceListF_CRP$`Percentile 75`,
                 finalRaceListF_CRP$Maximum)),
               n=c(finalRaceListF_CRP$Count[1],
                   finalRaceListF_CRP$Count[2],
                   finalRaceListF_CRP$Count[3],
                   finalRaceListF_CRP$Count[4],
                   finalRaceListF_CRP$Count[5]))

                

bxp(fStats, show.names = FALSE, main="Measure of hsCRP by Race (female)", xlab="hsCRP(mg/L)", ylab="Race", ylim = c(0,10), horizontal = TRUE)
axis(2, at = 1:5, labels = c("Asian", "Hisp.", "Black", "White", "All"))

```
```{r diseaseFrequencyCVD}
# Frequency of Cardiovascular Disease (CVD) diagnoses 
# Bar graph 
finalRaceListF_CVD <- finalRaceListF %>% 
  slice(1, 7, 13, 19, 25) 

finalRaceListF_CVD_bar <- ggplot(finalRaceListF_CVD, aes(x=Race, y=Mean, fill=Race)) + 
  geom_bar(stat="identity") + 
  ylim(0,0.2) + 
  labs(title = "Diagnosis of CVD by Race (Female)", x = "Race (Female)")
finalRaceListF_CVD_bar
```

```{r diseaseFrequencyD}
# Frequency of Diabetes diagnoses
# Bar graph 
finalRaceListF_D <- finalRaceListF %>% 
  slice(2, 8, 14, 20, 26)

finalRaceListF_D_bar <- ggplot(finalRaceListF_D, aes(x=Race, y=Mean, fill=Race)) + 
  geom_bar(stat="identity") + 
  ylim(0, 0.12) + 
  labs(title="Diagnosis of Diabetes by Race (Female)")
finalRaceListF_D_bar
```

```{r crpByDisease,echo=FALSE}
# Relationship between hsCRP and Cardiovascular Disease
# Bar graph 

# Relationship between hsCRP and Diabetes
# Bar graph 

```
