---
title: "CVD and Diabetes by Race"
output: html_document
date: '2022-12-29'
---
# Install Packages

```{r loadPackages, message = FALSE}
library(tidyverse)
library(readr)
```

# Load Data

```{r loadData, message = FALSE}
hispanic_df <- read_csv("Data/Hispanic.csv")
white_df <- read_csv("Data/Non_hispanic_white.csv")
black_df <- read_csv("Data/Non_hispanic_black.csv")
asian_df <- read_csv("Data/Asians.csv")
```

# Tidy Data 
 Column "Race" is added because there is not a column or row for race in the
 original CSVs, as each CSV only included data from one race.
 Column "...1" is renamed for clarity.

```{r tidyData, message = FALSE}
clean_asian_df <- mutate(asian_df, Race = "Asian") %>%
  rename(Question = ...1) %>%
  filter(Question %in% c(
    "Diagnosed with any CVD",
    "Ever diagnosed with diabetes W5"
    ))

clean_black_df <- mutate(black_df, Race = "Black") %>%
  rename(Question = ...1) %>%
  filter(Question %in% c(
    "Diagnosed with any CVD",
    "Ever diagnosed with diabetes W5"
    ))

clean_hispanic_df <- mutate(hispanic_df, Race = "Hispanic") %>%
  rename(Question = ...1) %>%
  filter(Question %in% c(
    "Diagnosed with any CVD",
    "Ever diagnosed with diabetes W5"
    ))

clean_white_df <- mutate(white_df, Race = "White") %>%
  rename(Question = ...1) %>%
  filter(Question %in% c(
    "Diagnosed with any CVD",
    "Ever diagnosed with diabetes W5"
    ))
```

# Join Dataframes 
```{r joinDataframes, message = FALSE}
asian_and_black_df <- rbind(clean_asian_df, clean_black_df)
hispanic_and_white_df <- rbind(clean_hispanic_df, clean_white_df)
all_races_df <- rbind(asian_and_black_df, hispanic_and_white_df)
```

# Visualize 
```{r visualizeDataframe, message = FALSE}
# https://www.statology.org/ggplot2-barplot-with-multiple-variables/

ggplot(all_races_df, aes(fill=Question, y=Mean, x=Race)) +
  geom_bar(position='dodge', stat='identity') +
  ggtitle('CVD & Diabetes Diagnosis by Race') +
  labs(x = "Race", y = "Percentage of Sample Diagnosed") +
  scale_fill_manual('Diagnosis', values=c('firebrick3','cornflowerblue'))
  
```